### ISSUE TITLE
Hello Vista1nik

### ISSUE THREAD

**Issue by Flyx33** [Vista1nik/ThunderDocs#11]
Hello Vista1nik, I am a front-end developer in training for back-end and am looking into learning to use electron. I feel that me and you could teach each other some things and maybe I could even help you on ThunderDocs! And, my apologies but this is the best way I could find to contact you. Please DM me on twitter, https://twitter.com/whyisminetaken, or email at jaronpate@gmail.com, or respond here if you're interested in making acquaintances.

**Comment by Vista1nik** [comment]
Sorry, my English is very bad. 
I have very little knowledge about electron.

 I recommend this 
- https://electronjs.org/docs/tutorial/first-app 
- https://www.christianengvall.se/category/electron/
