### ISSUE TITLE
Linux build?

### ISSUE THREAD

**Issue by arjvik** [Vista1nik/ThunderDocs#25]
Hi,
This app looks great, but it doesn't have a Linux build. I would really like to use it, but would rather not install npm and electron on my laptop since I have very little disk space remaining. Can you please publish a Linux build?

**Comment by Vista1nik** [comment]
Hello @arjvik 
Now you can download linux build. [Click here](https://github.com/Vista1nik/ThunderDocs/releases/tag/1.5.0-linux)

**Comment by arjvik** [comment]
Thanks! I will try this later.

**Comment by arjvik** [comment]
It works! Thanks!
