### ISSUE TITLE
Google Docs Extension

### ISSUE THREAD

**Issue by vanbwodonk** [Vista1nik/ThunderDocs#30]
== just asking==

I need  for offline editing & copy paste support.
Can thunderDocs using google docs extension?

**Comment by Vista1nik** [comment]
Hello @vanbwodonk 
Unfortunately, [Electron](https://github.com/electron/electron) does not support chrome extensions.
See [Extension Issue](https://github.com/electron/electron/issues/13123#issuecomment-394300926) for more information.

Have a nice day 😄
