### ISSUE TITLE
A new icon?

### ISSUE THREAD

**Issue by DartPower** [Vista1nik/ThunderDocs#33]
Maybe you  make a another icon? Black card with lighting not a good idea :(

Maybe make like this? 👍 
https://electronjs.org/node_modules/electron-apps/apps/thunderdocs/thunderdocs-icon-128.png

**Comment by DartPower** [comment]
Maybe this variant for the originality? Original GoogleDrive App icons (ICO&PNG variants)
[GDRiveIcons.zip](https://github.com/Vista1nik/ThunderDocs/files/2684544/GDRiveIcons.zip)

**Comment by Vista1nik** [comment]
Hello @DartPower. I agreed with your opinion, but I can't use Google Documents Icon.
I Working on an improvement of the old icon.
